import dotenv from 'dotenv';
dotenv.config();

import { connectDatabase } from '../config/database';
import { User } from '../models/User.model';
import { Product } from '../models/Product.model';
import { logger } from '../utils/logger.util';
import { USER_ROLES } from '../config/constants';

const seedUsers = [
  {
    firstName: 'Admin',
    lastName: 'User',
    email: 'admin@ecommerce.com',
    password: 'Admin@123',
    role: USER_ROLES.ADMIN,
    addresses: [],
  },
  {
    firstName: 'John',
    lastName: 'Customer',
    email: 'customer@ecommerce.com',
    password: 'Customer@123',
    role: USER_ROLES.CUSTOMER,
    addresses: [
      {
        street: '123 Main St',
        city: 'New York',
        state: 'NY',
        zipCode: '10001',
        country: 'USA',
        isDefault: true,
      },
    ],
  },
];

const seedProducts = [
  // Electronics
  {
    name: 'MacBook Pro 16"',
    slug: 'macbook-pro-16',
    description: 'Powerful laptop with M3 Pro chip, 16GB RAM, and 512GB SSD. Perfect for professionals.',
    price: 2499,
    comparePrice: 2799,
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400'],
    category: 'Electronics',
    brand: 'Apple',
    sku: 'ELEC-001',
    stock: 25,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'iPhone 15 Pro',
    slug: 'iphone-15-pro',
    description: 'Latest iPhone with A17 Pro chip, 128GB storage, and titanium design.',
    price: 999,
    comparePrice: 1099,
    images: ['https://images.unsplash.com/photo-1592286927505-a47e26f03e33?w=400'],
    category: 'Electronics',
    brand: 'Apple',
    sku: 'ELEC-002',
    stock: 50,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Sony WH-1000XM5 Headphones',
    slug: 'sony-wh-1000xm5',
    description: 'Industry-leading noise canceling headphones with superior sound quality.',
    price: 399,
    comparePrice: 449,
    images: ['https://images.unsplash.com/photo-1545127398-14699f92334b?w=400'],
    category: 'Electronics',
    brand: 'Sony',
    sku: 'ELEC-003',
    stock: 40,
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Samsung Galaxy S24 Ultra',
    slug: 'samsung-galaxy-s24-ultra',
    description: 'Premium Android phone with 200MP camera and S Pen.',
    price: 1199,
    comparePrice: 1299,
    images: ['https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400'],
    category: 'Electronics',
    brand: 'Samsung',
    sku: 'ELEC-004',
    stock: 30,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Dell XPS 13 Laptop',
    slug: 'dell-xps-13',
    description: 'Compact and powerful ultrabook with 13.4" display and Intel Core i7.',
    price: 1499,
    comparePrice: 1699,
    images: ['https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400'],
    category: 'Electronics',
    brand: 'Dell',
    sku: 'ELEC-005',
    stock: 20,
    isActive: true,
    isFeatured: false,
  },
  // Clothing
  {
    name: 'Classic Cotton T-Shirt',
    slug: 'classic-cotton-tshirt',
    description: 'Comfortable 100% cotton t-shirt in multiple colors. Perfect for everyday wear.',
    price: 29.99,
    comparePrice: 39.99,
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400'],
    category: 'Clothing',
    brand: 'BasicWear',
    sku: 'CLO-001',
    stock: 100,
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Slim Fit Jeans',
    slug: 'slim-fit-jeans',
    description: 'Modern slim fit jeans with stretch denim for comfort.',
    price: 79.99,
    comparePrice: 99.99,
    images: ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=400'],
    category: 'Clothing',
    brand: 'DenimCo',
    sku: 'CLO-002',
    stock: 75,
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Leather Jacket',
    slug: 'leather-jacket',
    description: 'Premium genuine leather jacket with classic design.',
    price: 299,
    comparePrice: 399,
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400'],
    category: 'Clothing',
    brand: 'UrbanStyle',
    sku: 'CLO-003',
    stock: 30,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Running Shoes',
    slug: 'running-shoes',
    description: 'Lightweight running shoes with advanced cushioning technology.',
    price: 129.99,
    comparePrice: 159.99,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400'],
    category: 'Clothing',
    brand: 'SportMax',
    sku: 'CLO-004',
    stock: 60,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Winter Coat',
    slug: 'winter-coat',
    description: 'Warm and stylish winter coat with water-resistant fabric.',
    price: 199,
    comparePrice: 249,
    images: ['https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=400'],
    category: 'Clothing',
    brand: 'WinterWear',
    sku: 'CLO-005',
    stock: 40,
    isActive: true,
    isFeatured: false,
  },
  // Home & Garden
  {
    name: 'Modern Desk Lamp',
    slug: 'modern-desk-lamp',
    description: 'Adjustable LED desk lamp with touch controls and multiple brightness levels.',
    price: 49.99,
    comparePrice: 69.99,
    images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400'],
    category: 'Home & Garden',
    brand: 'LightHome',
    sku: 'HOM-001',
    stock: 50,
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Ergonomic Office Chair',
    slug: 'ergonomic-office-chair',
    description: 'Comfortable office chair with lumbar support and adjustable height.',
    price: 349,
    comparePrice: 449,
    images: ['https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=400'],
    category: 'Home & Garden',
    brand: 'ErgoFit',
    sku: 'HOM-002',
    stock: 25,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Indoor Plant Set',
    slug: 'indoor-plant-set',
    description: 'Set of 3 easy-care indoor plants with decorative pots.',
    price: 59.99,
    comparePrice: 79.99,
    images: ['https://images.unsplash.com/photo-1459156212016-c812468e2115?w=400'],
    category: 'Home & Garden',
    brand: 'GreenLife',
    sku: 'HOM-003',
    stock: 45,
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Smart Coffee Maker',
    slug: 'smart-coffee-maker',
    description: 'Wi-Fi enabled coffee maker with programmable brewing and voice control.',
    price: 149,
    comparePrice: 199,
    images: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400'],
    category: 'Home & Garden',
    brand: 'SmartHome',
    sku: 'HOM-004',
    stock: 35,
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Memory Foam Mattress',
    slug: 'memory-foam-mattress',
    description: 'Queen size memory foam mattress with cooling gel technology.',
    price: 599,
    comparePrice: 799,
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400'],
    category: 'Home & Garden',
    brand: 'SleepWell',
    sku: 'HOM-005',
    stock: 15,
    isActive: true,
    isFeatured: true,
  },
  // Sports
  {
    name: 'Yoga Mat Premium',
    slug: 'yoga-mat-premium',
    description: 'Extra thick yoga mat with non-slip surface and carrying strap.',
    price: 39.99,
    comparePrice: 49.99,
    images: ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400'],
    category: 'Sports',
    brand: 'YogaLife',
    sku: 'SPO-001',
    stock: 80,
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Adjustable Dumbbells',
    slug: 'adjustable-dumbbells',
    description: 'Space-saving adjustable dumbbells with weight range 5-52.5 lbs.',
    price: 299,
    comparePrice: 399,
    images: ['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400'],
    category: 'Sports',
    brand: 'FitnessPro',
    sku: 'SPO-002',
    stock: 30,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Mountain Bike',
    slug: 'mountain-bike',
    description: '27.5" mountain bike with 21-speed gear system and dual suspension.',
    price: 499,
    comparePrice: 649,
    images: ['https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=400'],
    category: 'Sports',
    brand: 'TrailRider',
    sku: 'SPO-003',
    stock: 20,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Tennis Racket Pro',
    slug: 'tennis-racket-pro',
    description: 'Professional-grade tennis racket with graphite frame.',
    price: 179,
    comparePrice: 229,
    images: ['https://images.unsplash.com/photo-1617083278638-14fe1c103ead?w=400'],
    category: 'Sports',
    brand: 'CourtKing',
    sku: 'SPO-004',
    stock: 40,
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Resistance Bands Set',
    slug: 'resistance-bands-set',
    description: 'Set of 5 resistance bands with different resistance levels and accessories.',
    price: 29.99,
    comparePrice: 39.99,
    images: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=400'],
    category: 'Sports',
    brand: 'FitnessPro',
    sku: 'SPO-005',
    stock: 70,
    isActive: true,
    isFeatured: false,
  },
  // Books
  {
    name: 'The Psychology of Money',
    slug: 'psychology-of-money',
    description: 'Timeless lessons on wealth, greed, and happiness.',
    price: 24.99,
    comparePrice: 29.99,
    images: ['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400'],
    category: 'Books',
    brand: 'Financial Press',
    sku: 'BOO-001',
    stock: 100,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Atomic Habits',
    slug: 'atomic-habits',
    description: 'An easy and proven way to build good habits and break bad ones.',
    price: 19.99,
    comparePrice: 24.99,
    images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400'],
    category: 'Books',
    brand: 'Self-Help Publishing',
    sku: 'BOO-002',
    stock: 120,
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Clean Code',
    slug: 'clean-code',
    description: 'A handbook of agile software craftsmanship.',
    price: 39.99,
    comparePrice: 49.99,
    images: ['https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400'],
    category: 'Books',
    brand: 'Tech Books',
    sku: 'BOO-003',
    stock: 60,
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Sapiens',
    slug: 'sapiens',
    description: 'A brief history of humankind from Stone Age to modern times.',
    price: 22.99,
    comparePrice: 27.99,
    images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400'],
    category: 'Books',
    brand: 'History Press',
    sku: 'BOO-004',
    stock: 80,
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'The Lean Startup',
    slug: 'lean-startup',
    description: 'How today\'s entrepreneurs use continuous innovation to create radically successful businesses.',
    price: 26.99,
    comparePrice: 32.99,
    images: ['https://images.unsplash.com/photo-1513001900722-370f803f498d?w=400'],
    category: 'Books',
    brand: 'Business Publishing',
    sku: 'BOO-005',
    stock: 90,
    isActive: true,
    isFeatured: false,
  },
];

async function seedDatabase() {
  try {
    await connectDatabase();

    logger.info('Clearing existing data...');
    await Promise.all([
      User.deleteMany({}),
      Product.deleteMany({}),
    ]);

    logger.info('Seeding users...');
    await User.insertMany(seedUsers);
    logger.info(`Created ${seedUsers.length} users`);

    logger.info('Seeding products...');
    await Product.insertMany(seedProducts);
    logger.info(`Created ${seedProducts.length} products`);

    logger.info('Database seeded successfully!');
    logger.info('\nSample Credentials:');
    logger.info('Admin - Email: admin@ecommerce.com, Password: Admin@123');
    logger.info('Customer - Email: customer@ecommerce.com, Password: Customer@123');

    process.exit(0);
  } catch (error) {
    logger.error('Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase();
